# Generated by Django 5.2.8 on 2025-12-02 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the TODO item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the TODO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the TODO', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the TODO', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for the TODO', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the TODO was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the TODO was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the TODO was completed', null=True)),
                ('owner', models.ForeignKey(help_text='User who owns this TODO', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
                'ordering': ['-created_at'],
            },
        ),
    ]
